/* GENERATED by tools/sync-mobile-shared.mjs from web/src/lib/listing-evidence.ts. Do not edit here. */
/**
 * Evidence layer — the derived facts behind the panels on a listing page.
 *
 * Pure functions over a stored listing plus its comparables. No DOM, no
 * Prisma imports: the page fetches, this computes, the components render.
 *
 * ONE RULE RUNS THROUGH ALL OF IT. On the static site these facts were derived
 * from a hash of the listing id, because that catalogue is seeded demo data
 * and consistency was the only requirement. Against a real database that would
 * be fabrication — a made-up "no shared-identity clustering: pass" on a
 * stranger's listing is not a softer version of the truth, it is a false
 * statement about a real person's home that a renter may act on.
 *
 * So everything here is computed from stored columns or reported as not run.
 * Checks the platform does not actually perform yet say so. That makes the
 * trust panel less impressive and considerably more useful.
 */

import {
  allInOf,
  monthlyFees,
  rulesFor,
  toUsd,
  type Fee,
  type Rules,
  type Source,
} from "./listing-rules";

/* ------------------------------------------------------------------------ */

export type EvidenceListing = {
  id: string;
  title: string;
  address: string;
  neighborhood: string;
  cityId: string;
  citySlug: string;
  cityName: string;
  cityState: string;
  cityCountry: string;
  currency: string;
  housingType: string;
  price: number;
  allIn: number;
  allInUsd: number;
  deposit: number;
  sqft: number;
  feesJson: string;
  amenitiesJson: string;
  accessibilityJson: string;
  listedBy: string;
  addressPrivacy: string;
  verified: boolean;
  vouchersAccepted: boolean;
  registrationNumber: string | null;
  availableFrom: string;
  availableUntil: string | null;
  minStayMonths: number;
  maxStayMonths: number;
  leaseEnd: string | null;
  takeoverType: string | null;
  consentStatus: string | null;
  status: string;
  sponsored: boolean;
  updatedAt: Date;
};

export type PeerPrice = { allInUsd: number; housingType: string; cityId: string };

/* --- parsing ------------------------------------------------------------ */

export function parseFees(json: string): Fee[] {
  try {
    const parsed = JSON.parse(json) as unknown;
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter((f): f is Record<string, unknown> => !!f && typeof f === "object")
      .map((f) => ({
        type: String(f.type || ""),
        amount: Number(f.amount) || 0,
        cadence: f.cadence === "once" ? ("once" as const) : ("monthly" as const),
        mandatory: f.mandatory !== false,
      }))
      .filter((f) => !!f.type);
  } catch {
    return [];
  }
}

export function parseList(json: string): string[] {
  try {
    const parsed = JSON.parse(json) as unknown;
    return Array.isArray(parsed) ? parsed.filter((x): x is string => typeof x === "string") : [];
  } catch {
    return [];
  }
}

/* --- price truth -------------------------------------------------------- */

export type PriceTruth = {
  n: number;
  percentile: number;
  vsMedian: number;
  p10: number;
  p25: number;
  p50: number;
  p75: number;
  p90: number;
  mine: number;
  perSqftAnnual: number | null;
  feesAdd: number;
  feesPct: number;
  tone: "under" | "at" | "over";
  /** Too few comparables to say anything honest. */
  thin: boolean;
  /** Whether the pool had to widen past this city to reach a usable size. */
  scope: "city" | "type";
};

export function priceTruth(listing: EvidenceListing, peers: PeerPrice[]): PriceTruth | null {
  let scope: PriceTruth["scope"] = "city";
  let pool = peers.filter((p) => p.cityId === listing.cityId && p.housingType === listing.housingType);
  if (pool.length < 6) {
    pool = peers.filter((p) => p.housingType === listing.housingType);
    scope = "type";
  }

  const values = pool.map((p) => p.allInUsd).filter((v) => v > 0).sort((a, b) => a - b);
  /* Below this, a percentile is noise dressed as a number. Say nothing rather
     than tell someone they are in the 80th percentile of four listings. */
  if (values.length < 4) return null;

  const q = (t: number) => {
    const i = (values.length - 1) * t;
    const lo = Math.floor(i);
    const hi = Math.ceil(i);
    return Math.round(values[lo] + (values[hi] - values[lo]) * (i - lo));
  };

  const mine = listing.allInUsd || toUsd(listing.allIn, listing.currency);
  const below = values.filter((v) => v < mine).length;
  const percentile = values.length > 1 ? Math.round((below / (values.length - 1)) * 100) : 50;
  const p50 = q(0.5);
  const vsMedian = p50 ? Math.round(((mine - p50) / p50) * 100) : 0;
  const fees = monthlyFees(parseFees(listing.feesJson));

  return {
    n: values.length,
    percentile: Math.max(0, Math.min(100, percentile)),
    vsMedian,
    p10: q(0.1),
    p25: q(0.25),
    p50,
    p75: q(0.75),
    p90: q(0.9),
    mine,
    perSqftAnnual: listing.sqft ? Math.round((listing.allIn / listing.sqft) * 12 * 100) / 100 : null,
    feesAdd: fees,
    feesPct: listing.price ? Math.round((fees / listing.price) * 100) : 0,
    tone: vsMedian <= -8 ? "under" : vsMedian >= 12 ? "over" : "at",
    thin: values.length < 12,
    scope,
  };
}

/* --- the deal ----------------------------------------------------------- */

export type Deal = {
  kind: string;
  label: string;
  short: string;
  blurb: string;
  brokerInDeal: boolean;
  byOwner: boolean;
  byDepartingTenant: boolean;
};

const DEALS: Record<string, Omit<Deal, "kind" | "byOwner" | "byDepartingTenant">> = {
  owner: {
    label: "Listed by the owner",
    short: "By owner",
    blurb:
      "The person letting this home owns it and is handling the let themselves. There is no agent in the transaction, so there is no broker fee to argue about.",
    brokerInDeal: false,
  },
  manager: {
    label: "Listed by a managing agent",
    short: "Managed",
    blurb:
      "An agent or management company lets this on the owner’s behalf. They act for the owner, not for you.",
    brokerInDeal: true,
  },
  tenant: {
    label: "Listed by the departing tenant",
    short: "Takeover",
    blurb:
      "The current tenant is leaving and passing the home on. Whether they stay liable depends on whether this is a sublet or an assignment — the desk below sets that out.",
    brokerInDeal: false,
  },
};

export function dealFor(listing: EvidenceListing): Deal {
  const kind = DEALS[listing.listedBy] ? listing.listedBy : "owner";
  const base = DEALS[kind];
  return {
    kind,
    ...base,
    byOwner: kind === "owner",
    byDepartingTenant: kind === "tenant",
  };
}

/* --- fee legality ------------------------------------------------------- */

export type FeeVerdict = {
  key: string;
  label: string;
  amount: number;
  cadence: "monthly" | "once";
  state: "ok" | "capped" | "over" | "barred";
  why: string;
  src: Source | null;
};

const FEE_LABELS: Record<string, string> = {
  broker: "Broker fee",
  application: "Application fee",
  screening: "Background & credit",
  utilities: "Utilities",
  wifi: "Wi-Fi",
  cleaning: "Cleaning",
  parking: "Parking",
  amenity: "Amenity fee",
  storage: "Storage",
  pet: "Pet rent",
  admin: "Admin fee",
  move_in: "Move-in fee",
  key: "Key fee",
  access: "Takeover access fee",
};

const MOVE_IN_TYPES = ["admin", "move_in", "key", "access"];

export function feeVerdicts(listing: EvidenceListing, rules: Rules, deal: Deal): FeeVerdict[] {
  const fees = parseFees(listing.feesJson);
  const out: FeeVerdict[] = [];

  for (const f of fees) {
    const label = FEE_LABELS[f.type] || f.type;
    let state: FeeVerdict["state"] = "ok";
    let why = "A recurring charge, inside the all-in figure.";
    let src: Source | null = null;

    if (f.type === "broker") {
      if (f.amount > 0 && !rules.landlordAgentMayChargeTenant) {
        state = "barred";
        src = rules.tenantBrokerFeeSrc;
        why = deal.brokerInDeal
          ? "The broker here acts for the landlord, and a landlord’s agent may not charge you in this market. A broker you retained yourself is a different matter."
          : "A landlord’s agent may not charge the tenant here.";
      } else if (f.amount > 0) {
        why = "Lawful in this market, and disclosed on the listing rather than produced at signing.";
      } else {
        why = deal.brokerInDeal ? "No broker fee is being passed to you." : "There is no broker in this deal.";
      }
    } else if (MOVE_IN_TYPES.includes(f.type) && f.amount > 0) {
      if (rules.moveInFeesBarred) {
        state = "barred";
        src = rules.moveInFeesSrc;
        why =
          deal.byDepartingTenant && rules.subLessorNamed
            ? "The statute naming sub-lessors as well as landlords bars a charge of this kind at the start of a tenancy, so a departing tenant cannot levy it either."
            : "A charge demanded before or at the start of the tenancy is not permitted here.";
      } else {
        why = "Permitted, and disclosed up front.";
      }
    } else if (f.type === "application" && f.amount > 0 && rules.applicationFeeBanned) {
      state = "barred";
      src = rules.applicationFeeSrc;
      why = "An application, processing or acceptance fee may not be demanded in this market at all.";
    }

    out.push({ key: f.type, label, amount: f.amount, cadence: f.cadence, state, why, src });
  }

  /* The deposit is not a fee, but it is the largest sum changing hands and the
     one this platform most needs to be clear it does not hold. */
  if (listing.deposit > 0) {
    const cap = rules.depositCapMonths != null ? Math.round(listing.price * rules.depositCapMonths) : null;
    out.push({
      key: "deposit",
      label: "Security deposit",
      amount: listing.deposit,
      cadence: "once",
      state: cap != null ? (listing.deposit > cap ? "over" : "capped") : "ok",
      why:
        `Paid direct to ${deal.byDepartingTenant ? "the departing tenant or the building’s owner" : deal.byOwner ? "the owner" : "the landlord"}. ` +
        "RentLeaks does not hold it and cannot return it." +
        (cap != null
          ? ` Capped here at ${rules.depositCapMonths} month${rules.depositCapMonths === 1 ? "" : "s"} of rent, and the cap reaches advances too.`
          : ""),
      src: rules.depositSrc,
    });
  }

  return out;
}

/* --- trust -------------------------------------------------------------- */

export type TrustRow = {
  key: string;
  state: "pass" | "warn" | "none" | "not-run";
  what: string;
  how: string;
};

export type Trust = { rows: TrustRow[]; passed: number; scored: number; notRun: number };

/**
 * What we can actually say. `verified` is a real column; the rest are checks
 * the platform has not built yet, and they are reported as not run rather than
 * quietly passing. A trust panel that invents its own evidence is worse than
 * no trust panel, because renters act on it.
 */
export function trustFor(listing: EvidenceListing): Trust {
  const rows: TrustRow[] = [
    {
      key: "identity",
      state: listing.verified ? "pass" : "none",
      what: "Government ID matched to the account name",
      how: listing.verified
        ? "Document and selfie checked, name matched, and the image discarded after the match."
        : "Not completed. This host can list and message, but has not proven who they are.",
    },
    {
      key: "control",
      state: "not-run",
      what: "Control of the address proven",
      how:
        "Not yet checked on this listing. Ownership documents are collected in the verification desk; matching them against the address automatically is not built yet, so we do not claim it here.",
    },
    {
      key: "media",
      state: "not-run",
      what: "Photographs unique to this listing",
      how:
        "Perceptual-hash duplicate detection is not running yet. Until it is, treat stock-looking photographs as a reason to ask for a live walkthrough.",
    },
    {
      key: "freshness",
      state: freshness(listing.updatedAt),
      what: "Listing confirmed by the host",
      how: freshnessNote(listing.updatedAt),
    },
    {
      key: "money",
      state: "pass",
      what: "RentLeaks never handles your money",
      how:
        "No deposit, no booking fee, no application fee — there is nothing to pay us, ever. Anyone asking you to pay RentLeaks is running a scam, with no exceptions.",
    },
  ];

  /* Counts, not a score out of a hundred.
     A percentage computed over only the checks that ran renders "100" on a
     listing where control of the address has never been verified, and no
     caption underneath undoes what a big round number tells a reader. Three
     of five, with the two unrun ones named, says the same thing without
     overclaiming. */
  const scored = rows.filter((r) => r.state !== "not-run").length;
  const passed = rows.filter((r) => r.state === "pass").length;
  return { rows, passed, scored, notRun: rows.length - scored };
}

function daysSince(d: Date) {
  return Math.floor((Date.now() - d.getTime()) / 86_400_000);
}

function freshness(updatedAt: Date): TrustRow["state"] {
  return daysSince(updatedAt) <= 14 ? "pass" : "warn";
}

function freshnessNote(updatedAt: Date) {
  const days = daysSince(updatedAt);
  return days <= 14
    ? `Last updated ${days} day${days === 1 ? "" : "s"} ago.`
    : `Last updated ${days} days ago. Ask whether it is still free before arranging a viewing.`;
}

/* --- takeover ----------------------------------------------------------- */

export type Takeover = {
  mode: "sublet" | "assignment";
  consent: string;
  remainingMonths: number;
  clockApplies: boolean;
  statute: string | null;
  appliesTo: string | null;
  infoWindowDays: number | null;
  decisionWindowDays: number | null;
  assignmentNote: string | null;
  accessFeeAllowed: boolean;
  accessFeeSrc: Source | null;
  screeningCap: number | null;
  depositCapMonths: number | null;
  surchargePct: number | null;
  surchargeSrc: Source | null;
  licenceRisk: "high" | "moderate";
};

export function takeoverFor(listing: EvidenceListing, rules: Rules): Takeover | null {
  if (listing.housingType !== "lease-break") return null;

  const mode = listing.takeoverType === "assignment" ? "assignment" : "sublet";
  const sublet = rules.sublet;
  /* The statutory clock attaches to subletting. Showing a countdown on an
     assignment, which has no deemed-consent rule, would be worse than showing
     nothing at all. */
  const clockApplies = mode === "sublet" && !!sublet?.silenceIsConsent;

  const remaining = listing.leaseEnd
    ? Math.max(0, Math.round((new Date(`${listing.leaseEnd}T00:00:00`).getTime() - Date.now()) / (86_400_000 * 30)))
    : 0;

  return {
    mode,
    consent: listing.consentStatus || "pending",
    remainingMonths: remaining,
    clockApplies,
    statute: sublet?.statute || null,
    appliesTo: sublet?.appliesTo || null,
    infoWindowDays: clockApplies ? sublet?.infoWindowDays ?? null : null,
    decisionWindowDays: clockApplies ? sublet?.decisionWindowDays ?? null : null,
    assignmentNote: sublet?.assignmentNote || null,
    accessFeeAllowed: !(rules.moveInFeesBarred && rules.subLessorNamed),
    accessFeeSrc: rules.moveInFeesSrc,
    screeningCap: rules.screeningFeeCap,
    depositCapMonths: rules.depositCapMonths,
    surchargePct: mode === "sublet" ? rules.subletSurchargePct : null,
    surchargeSrc: rules.subletSurchargeSrc,
    licenceRisk: mode === "assignment" ? "high" : "moderate",
  };
}

/* --- compliance --------------------------------------------------------- */

export type ComplianceRow = { k: string; detail: string; value: string; pass: boolean; src: Source | null };

export function complianceFor(listing: EvidenceListing, rules: Rules, fmt: (n: number) => string): ComplianceRow[] {
  const rows: ComplianceRow[] = [];
  const fees = parseFees(listing.feesJson);
  const broker = fees.filter((f) => f.type === "broker").reduce((a, f) => a + f.amount, 0);

  if (!rules.landlordAgentMayChargeTenant) {
    rows.push({
      k: "Broker fee charged to you",
      detail: "A landlord’s agent may not charge the tenant in this market",
      value: broker ? fmt(broker) : "None",
      pass: broker === 0,
      src: rules.tenantBrokerFeeSrc,
    });
  }
  if (rules.depositCapMonths != null) {
    const cap = Math.round(listing.price * rules.depositCapMonths);
    rows.push({
      k: "Security deposit",
      detail: `Capped at ${rules.depositCapMonths} month${rules.depositCapMonths === 1 ? "" : "s"} of base rent — ${fmt(cap)}`,
      value: fmt(listing.deposit),
      pass: listing.deposit <= cap,
      src: rules.depositSrc,
    });
  }
  if (rules.applicationFeeBanned) {
    rows.push({
      k: "Application fee",
      detail: `May not be demanded at all; background and credit capped at ${fmt(rules.screeningFeeCap || 20)}`,
      value: fmt(fees.filter((f) => f.type === "application").reduce((a, f) => a + f.amount, 0)),
      pass: !fees.some((f) => f.type === "application" && f.amount > 0),
      src: rules.applicationFeeSrc,
    });
  }

  const minDays = Math.max(1, listing.minStayMonths * 30);
  rows.push({
    k: "Minimum stay",
    detail: `Market floor ${rules.minStayDays} days · this listing asks ${minDays}`,
    value: `${minDays} days`,
    pass: minDays >= rules.minStayDays,
    src: rules.minStaySrc,
  });

  if (rules.registrationRequired) {
    rows.push({
      k: "Registration number",
      detail: "Published on the listing and reported to the registry",
      value: listing.registrationNumber || "Missing",
      pass: !!listing.registrationNumber,
      src: rules.registrationSrc,
    });
  }
  if (rules.soiProtected) {
    rows.push({
      k: "Housing vouchers",
      detail: "Refusing a lawful source of income is unlawful in this market",
      value: listing.vouchersAccepted ? "Accepted" : "Not stated",
      pass: listing.vouchersAccepted,
      src: rules.soiSrc,
    });
  }
  if (rules.allInDisclosure) {
    rows.push({
      k: "All-in price shown first",
      detail: "Every required fee inside the headline number",
      value: fmt(listing.allIn),
      pass: listing.allIn >= allInOf({ price: listing.price, fees }),
      src: rules.allInSrc,
    });
  }

  return rows;
}

/* --- availability ------------------------------------------------------- */

export function stayWindow(listing: EvidenceListing, rules: Rules) {
  const minDays = Math.max(rules.minStayDays, listing.minStayMonths * 30);
  const until = listing.availableUntil;
  const days =
    until && listing.availableFrom
      ? Math.round(
          (new Date(`${until}T00:00:00`).getTime() - new Date(`${listing.availableFrom}T00:00:00`).getTime()) /
            86_400_000,
        )
      : null;
  return { from: listing.availableFrom, until, minDays, days };
}

/* --- affordability ------------------------------------------------------ */

/**
 * Arithmetic on the posted price, not a claim about this renter.
 *
 * Worth stating plainly, because listing sites routinely print both as though
 * they were two different tests: the "40× the rent" screen landlords apply and
 * the "spend no more than 30% of gross" guideline are the SAME threshold.
 * 12 ÷ 0.30 = 40. Showing them as a pair, with a gap between them, would be
 * inventing a distinction — so this returns one gross figure, and the numbers
 * that actually differ from it: what that is per month, and the 80× a
 * guarantor is typically held to.
 */
export function affordabilityFor(listing: EvidenceListing) {
  const monthly = listing.allIn || listing.price;
  const annualGross = Math.round(monthly * 40);
  return {
    monthly,
    /** 40× monthly rent, which is identical to 30% of gross income. */
    annualGross,
    monthlyGross: Math.round(annualGross / 12),
    /** Rent as a share of a renter earning exactly the threshold. */
    sharePct: 30,
    guarantorAnnual: Math.round(monthly * 80),
  };
}

/* --- one call for a page ------------------------------------------------ */

export function evidenceFor(listing: EvidenceListing, peers: PeerPrice[], fmt: (n: number) => string) {
  const rules = rulesFor({
    cityId: listing.cityId,
    citySlug: listing.citySlug,
    cityName: listing.cityName,
    state: listing.cityState,
    country: listing.cityCountry,
  });
  const deal = dealFor(listing);
  return {
    rules,
    deal,
    price: priceTruth(listing, peers),
    fees: feeVerdicts(listing, rules, deal),
    trust: trustFor(listing),
    compliance: complianceFor(listing, rules, fmt),
    takeover: takeoverFor(listing, rules),
    window: stayWindow(listing, rules),
    afford: affordabilityFor(listing),
    allIn: allInOf({ price: listing.price, fees: parseFees(listing.feesJson) }),
    accessibility: parseList(listing.accessibilityJson),
  };
}

export type Evidence = ReturnType<typeof evidenceFor>;
