#!/usr/bin/env python3
"""
Adds the listing-title and counter patterns to locales/{fr,de,it}.json.

Every one of the 662 listing titles is generated by data.js from one of five
templates — see the `title = ...` assignments around lines 712-786. They are
not host-written prose, which is what the locale README says is off limits, so
they translate like any other product string. They are also the single most
visible text on the site: one per card, dozens per page.

The neighbourhood inside each title is a proper noun and stays put; only the
frame around it moves.

    python3 tools/add-title-patterns.py
"""
import collections
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (regex, fr, de, it) — inserted at the front, so they are tried before the
# generic rules. {2} is a neighbourhood: never sent through the dictionary.
P = [
    # data.js: 'Sunny private room in ' + nhood + ' share'
    (r"^Sunny private room in (.+) share$",
     "Chambre lumineuse en colocation à {1}",
     "Helles WG-Zimmer in {1}",
     "Camera luminosa in condivisione a {1}"),

    # data.js: 'Private room + bath in ' + nhood
    (r"^Private room \+ bath in (.+)$",
     "Chambre avec salle de bain privative à {1}",
     "Eigenes Zimmer mit Bad in {1}",
     "Camera con bagno privato a {1}"),

    # data.js: brand + ' · ' + (privateBath ? 'studio-style room' : 'classic room') + ' in ' + nhood
    (r"^(.+) · studio-style room in (.+)$",
     "{1} · chambre façon studio à {2}",
     "{1} · Zimmer im Studio-Stil in {2}",
     "{1} · camera in stile monolocale a {2}"),
    (r"^(.+) · classic room in (.+)$",
     "{1} · chambre classique à {2}",
     "{1} · klassisches Zimmer in {2}",
     "{1} · camera classica a {2}"),

    # data.js: beds + ' bed furnished ' + (beds === 1 ? 'apartment' : 'home') + ' in ' + nhood
    (r"^(\d+) bed furnished apartment in (.+)$",
     "Appartement meublé {1} chambre à {2}",
     "Möblierte Wohnung mit {1} Schlafzimmer in {2}",
     "Appartamento arredato con {1} camera a {2}"),
    (r"^(\d+) bed furnished home in (.+)$",
     "Logement meublé {1} chambres à {2}",
     "Möblierte Wohnung mit {1} Schlafzimmern in {2}",
     "Casa arredata con {1} camere a {2}"),

    # data.js: '1-month+ furnished stay · ' + nhood
    (r"^1-month\+ furnished stay · (.+)$",
     "Séjour meublé d'un mois et + · {1}",
     "Möblierter Aufenthalt ab 1 Monat · {1}",
     "Soggiorno arredato da 1 mese in su · {1}"),

    # data.js: (beds === 0 ? 'Serviced studio' : 'Serviced 1-bed') + ' · ' + nhood
    (r"^Serviced studio · (.+)$",
     "Studio avec services · {1}",
     "Serviced Studio · {1}",
     "Monolocale con servizi · {1}"),
    (r"^Serviced 1-bed · (.+)$",
     "Une chambre avec services · {1}",
     "Serviced Apartment mit 1 Schlafzimmer · {1}",
     "Bilocale con servizi · {1}"),

    # data.js: remainingMonths + '-month lease takeover · ' + nhood
    (r"^(\d+)-month lease takeover · (.+)$",
     "Reprise de bail de {1} mois · {2}",
     "Mietübernahme über {1} Monate · {2}",
     "Subentro di {1} mesi · {2}"),

    # Counters that sit beside the grids.
    (r"^(\d+) flexible homes$",
     "{1} logements flexibles",
     "{1} flexible Wohnungen",
     "{1} case flessibili"),
    (r"^(\d+) of (\d+) homes$",
     "{1} logements sur {2}",
     "{1} von {2} Wohnungen",
     "{1} case su {2}"),
    (r"^(\d+) homes?$",
     "{1} logements",
     "{1} Wohnungen",
     "{1} case"),
    (r"^homes$", "logements", "Wohnungen", "case"),
    (r"^(\d+) live homes$",
     "{1} logements en ligne",
     "{1} Wohnungen online",
     "{1} case online"),
]


def main():
    for i, code in enumerate(("fr", "de", "it")):
        path = os.path.join(ROOT, "locales", f"{code}.json")
        d = json.loads(io.open(path, encoding="utf-8").read(),
                       object_pairs_hook=collections.OrderedDict)
        have = {r["re"] for r in d["patterns"]}
        new = []
        for row in P:
            regex, to = row[0], row[1 + i]
            if regex in have:
                continue
            new.append(collections.OrderedDict([("re", regex), ("to", to)]))
        # Front of the list: a title template must win over the generic
        # "N homes" and "X in Y" rules, which would otherwise match first.
        d["patterns"] = new + d["patterns"]
        io.open(path, "w", encoding="utf-8").write(
            json.dumps(d, ensure_ascii=False, indent=2) + "\n")
        print(f"locales/{code}.json  +{len(new)} patterns  ->  {len(d['patterns'])} total")


if __name__ == "__main__":
    main()
