#!/usr/bin/env python3
"""
Renders the Instagram launch feed — 20 posts, one a day — from one spec file.

    python3 tools/build-ig-feed.py            # all of them
    python3 tools/build-ig-feed.py fee-maths  # just one, while you edit it

It writes three things:

  images/social/ig/NN-<id>.jpg   the art, in the site's own palette and type.
                                 These live in the website repo on purpose:
                                 Instagram's publishing API fetches an image by
                                 public URL, so the post's picture has to be a
                                 real file on rentleaks.com.
  marketing/social/IG-FEED.md    the captions, in order, to copy by hand.
  tools/social/ig-queue.json     the machine-readable queue the desk seeds from
                                 (web/scripts/seed-ig-queue.mjs).

JPEG, not PNG: the Instagram Graph API only accepts JPEG for an image post.

The art helpers come from tools/build-social-art.py, so a brand change happens
in one place and both the profile kit and the feed follow it.
"""
import importlib.util
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, "tools", "social", "ig-posts.json")
QUEUE = os.path.join(ROOT, "tools", "social", "ig-queue.json")
OUT = os.path.join(ROOT, "images", "social", "ig")
DOC = os.path.join(ROOT, "marketing", "social", "IG-FEED.md")
SITE = "https://rentleaks.com"
SIZE = (1080, 1350)          # 4:5, the tallest Instagram allows in the feed
CAPTION_LIMIT = 2200         # Instagram's own limit


def art():
    """tools/build-social-art.py, imported by path — its name has a dash."""
    path = os.path.join(ROOT, "tools", "build-social-art.py")
    spec = importlib.util.spec_from_file_location("rl_social_art", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def caption_of(post, defaults):
    """Caption, then the statute it rests on, then the hashtags."""
    parts = [post["caption"].strip()]
    if post.get("source"):
        parts.append("Source: " + post["source"])
    parts.append(post.get("hashtags", defaults.get("hashtags", "")).strip())
    text = "\n\n".join(p for p in parts if p)
    if len(text) > CAPTION_LIMIT:
        raise SystemExit(f"{post['id']}: caption is {len(text)} characters, over Instagram's {CAPTION_LIMIT}.")
    return text


def main():
    only = [a.lower() for a in sys.argv[1:]]
    spec = json.load(open(SPEC, encoding="utf-8"))
    defaults = spec.get("defaults", {})
    posts = spec["posts"]
    ids = [p["id"] for p in posts]
    if len(set(ids)) != len(ids):
        sys.exit("Two posts share an id — ids must be unique.")
    unknown = [o for o in only if o not in ids]
    if unknown:
        sys.exit(f"Unknown post(s): {', '.join(unknown)}. Have: {', '.join(ids)}")

    A = art()
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    queue, lines, made = [], [], []

    for n, post in enumerate(posts, 1):
        name = f"{n:02d}-{post['id']}.jpg"
        path = os.path.join(OUT, name)
        if not only or post["id"] in only:
            img = A.post_card(
                SIZE,
                post["kicker"],
                post["headline"].replace("<br/>", " "),
                post.get("sub", ""),
                post.get("chips", []),
                theme=post.get("theme", "night"),
                footer=post.get("footer", defaults.get("footer", "rentleaks.com")),
            )
            img.save(path, "JPEG", quality=88, optimize=True, progressive=True)
            made.append(name)
        caption = caption_of(post, defaults)
        queue.append(
            {
                "day": n,
                "id": post["id"],
                "image": f"{SITE}/images/social/ig/{name}",
                "link": post.get("link", SITE),
                "caption": caption,
            }
        )
        lines += [
            f"## Day {n} · {post['id']}",
            "",
            f"**Image:** `images/social/ig/{name}`  ·  **Link:** {post.get('link', SITE)}",
            "",
            "```",
            caption,
            "```",
            "",
        ]

    json.dump(queue, open(QUEUE, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    head = [
        "# Instagram — the first 20 days",
        "",
        "Generated by `tools/build-ig-feed.py` from `tools/social/ig-posts.json`.",
        "Edit the spec, not this file.",
        "",
        "One post a day, in this order. The queue the app publishes from is",
        "`tools/social/ig-queue.json`; seed it with `node web/scripts/seed-ig-queue.mjs`.",
        "",
        "House rules, every post: describe the home, never who should live in it.",
        "No sample listing is ever shown as a real home. Statutes are named where a",
        "post rests on one, and every legal post carries the not-legal-advice line.",
        "",
    ]
    open(DOC, "w", encoding="utf-8").write("\n".join(head + lines))

    print(f"Rendered {len(made)} of {len(posts)} images into images/social/ig/")
    print(f"  captions  -> {os.path.relpath(DOC, ROOT)}")
    print(f"  queue     -> {os.path.relpath(QUEUE, ROOT)} ({len(queue)} posts)")
    longest = max(queue, key=lambda q: len(q["caption"]))
    print(f"  longest caption: {len(longest['caption'])} / {CAPTION_LIMIT} ({longest['id']})")


if __name__ == "__main__":
    main()
